### PR TITLE
Remove deprecated language configuration from TypoScript

### PR DESCRIPTION
**Pull request by albig**
This is not needed anymore because it is done by site configuration.

### CODE REVIEW

**Review by dvoracek-slub — APPROVED** [review]
Looks good to me, and actually this seems to fix a bug that the `<html>` lang attribute would have been set to `de` irrespective of the actual language (at least it is like this on the DDEV system).

Another change that I noted is that now the `<html>` tag doesn't have the `class="no-js"` anymore. However, it doesn't look like the `no-js` class is actually used anywhere, so we may just drop it (and, in that case, remove the `$('html').removeClass('no-js');` from `SxndScripts.js`)?

**Comment by albig** [comment]
> Looks good to me, and actually this seems to fix a bug that the `<html>` lang attribute would have been set to `de` irrespective of the actual language (at least it is like this on the DDEV system).

The TypoScript settings overwrite the site configuration and it is deprecated. So, all pages in English still had the `de` lang attribute. I wasn't aware, that I had these settings still in sachsendigital. I remember other websites where I removed it already.

> Another change that I noted is that now the `<html>` tag doesn't have the `class="no-js"` anymore. However, it doesn't look like the `no-js` class is actually used anywhere, so we may just drop it (and, in that case, remove the `$('html').removeClass('no-js');` from `SxndScripts.js`)?

Don't know what this `class="no-js"` was good for. We set it in the TypoScript and removed it in JavaScript? Sounds like TYPO3 integrator didn't talked to designer ;-)

**Comment by dvoracek-slub** [comment]
In theory that `no-js` could be used to apply some CSS styles specificially when JavaScript is disabled (for example, hide or rearrange various elements). But currently we don't seem handle noscript environments anyways, so...

**Comment by albig** [comment]
> In theory that `no-js` could be used to apply some CSS styles specificially when JavaScript is disabled (for example, hide or rearrange various elements). But currently we don't seem handle noscript environments anyways, so...

Ok. So I removed this from `SxndScripts.js` and recompiled.

**Pull request merged**
